<?php include "head.php" ?>
<br><br><br><br><br><br><br>
<form action="add_author.php" method="post" name="frt">
    <table align="center">
        <tr>
            <td class="t2">Добавление нового автора</td>
            <td><input type="text" size="20" maxlength="20" name="author" value="
                <?= $_POST["author"]; ?>"></td>
        </tr>
        <tr>
            <td colspan="2" align="center"><input type="submit" name="action" value="Добавить"></td>
        </tr>
    </table>
</form>
<div style="text-align:center"><a href="index.php">Перейти на Главную</a></div>
<?php include "foot.php" ?>