<?php include "head.php" ?>
<center><h2>Список авторов</h2></center>
<table width=40% height=20% align="center" border=1>
    <tr align="center">
        <td>Автор</td>
        <td>Действия</td>
    </tr>
    <?php
    foreach ($authors as $author):?>
        <tr align="center">
        <td><a href="/authors_books.php?author_id=<?= $author['author_id'] ?>"><?= $author['author'] ?></a></td>
        <td><a href="delete_author.php?author_id=<?= $author['author_id'] ?>">Удалить</a></td>
        </tr>
    <?php endforeach; ?>
</table>
<div style="text-align:center"><a href="index.php">Перейти на Главную</a></div>
<?php include "foot.php" ?>
