<?php include "head.php" ?>
<center><h2>Список жанров</h2></center>
<table width=40% height=20% align="center" border=1>
    <tr align="center">
        <td>Жанр</td>
        <td>Действия</td>
    </tr>
    <?php
foreach ($genres as $genre){
    print "<tr align=\"center\">";
    print '<td><a href="genres_books.php?genre_id=' . $genre['id'] . '">' . $genre['genre'] . '</a></td>';
    print '<td><a href="delete_genre.php?genre_id=' . $genre['id'] . '">' . 'Удалить' . '</tr></td>';
    }
    ?>
</table>
<div style="text-align:center"><a href="index.php">Перейти на Главную</a></div>
<?php include "foot.php" ?>
