<?php
include '../classes/db.class.php';
?>
<html>
<head>
    <link rel="stylesheet" type="text/css" href="style.css"/>
</head>
<body>
<br><br>
<div style="text-align:center"><a href="add_author.php">Добавить автора</a></div>
<div style="text-align:center"><a href="add_genre.php">Добавить жанр</a></div>
<div style="text-align:center"><a href="add_book.php">Добавить книгу</a></div>
<div style="text-align:center"><a href="delete_author.php">Удалить автора</a></div>
<div style="text-align:center"><a href="delete_genre.php">Удалить жанр</a></div>
<center><h2>Книжный каталог</h2></center>
<table width=50% height=20% align="center" border=1>
    <tr align="center">
        <td>Название книги</td>
        <td>Автор</td>
        <td>Жанр</td>
        <td>Стоимость</td>
        <td colspan="2">Действия</td>
    </tr>
    <?php
    $bookObject = new Books(new Db());
    $books = $bookObject->getAllBooks();
    $authors = array();
    $genres = array();
    var_dump($books);
    foreach ($books as $book) :?>
        <tr align="center">
            <td><a href="form.php?book_id=<?= $book['book_id']?>"> <?= $book['title'] ?> </a></td>
            <td>
                <?php foreach ($book['authors'] as $author) {
                    $authors[] = '<a href="authors_books.php?author_id=' . $author['author_id'] . '">' . $author['author'] . '</a>';
                } ?>
                <?= implode(', ', $authors) ?>
            </td>
            <td>
                <?php foreach ($book['genres'] as $genre) {
                    $genres[] = '<a href="genres_books.php?genre_id=' . $genre['id'] . '">' .
                        $genre['genre'] . '</a>';
                }
                ?>
                <?= implode(', ',$genres) ?>
            </td>
            <td><?= $book['price']; ?></td>

            <td><a href="index.php?book_id=<?= $book['book_id'] ?>">Удалить</td>
            <td><a href="update_books.php?book_id=<?= $book['book_id'] ?>">Редактировать</td>

        </tr>
    <?php endforeach; ?>
</table>
</body>
</html>
