<?php
//var_dump($book);
?>
<?php include "head.php" ?>
<br><br>
<form action="update_books.php" method="post" name="frt">
    <input type="hidden" name="book_id" value="<?= $book['book_id']; ?>"/>
    <table align="center">
        <tr>
            <td class="t2">Название:</td>
            <td><input type="text" size="30" maxlength="30" name="title"
                       value="<?= $book['title']; ?>"></td>
        </tr>
        <tr>
            <td class="t2">Автор:</td>
            <td>
                <select name="author[]" multiple="multiple">
					<?php foreach ( $authors as $author ):
						$selected = array_search( $author['author_id'], array_column( $book['authors'], 'author_id' ) );
						?>
                        <option value="<?= $author['author_id'] ?>" <?= ( $selected !== false ) ? 'selected' : '' ?>><?= $author['author'] ?></option>
					<?php endforeach; ?>
                </select>
            </td>
        </tr>
        <tr>
            <td class="t2">Жанр:</td>
            <td>
                <select name="genre[]" multiple="multiple">
					<?php foreach ( $genres as $genre ):
						$selected = array_search( $genre['id'], array_column( $book['genres'], 'genre_id' ) );
						?>
                        <option value="<?= $genre['id'] ?>" <?= ( $selected !== false ) ? 'selected' : '' ?>><?= $genre['genre'] ?></option>';
					<?php endforeach; ?>
                </select>
            </td>
        </tr>
        <tr>
            <td class="t2">Цена:</td>
            <td><input type="text" size="20" maxlength="20" name="price"
                       value="<?= $book['price']; ?>"></td>
        </tr>
        <tr>
            <td class="t2">Описание:</td>
            <td><textarea name="description"><?= $book['description']; ?></textarea>
        </tr>
        <tr>
            <td colspan="2" align="center"><input type="submit" name="saveBookData" value="Сохранить изменеиня">
            </td>
        </tr>
    </table>
</form>
<div style="text-align:center"><a href="index.php">Перейти на Главную</a></div>
<?php include "foot.php" ?>