<html>
<head>
    <link rel="stylesheet" type="text/css" href="style.css"/>
</head>
<body>
<br><br>
<center><h2>Книжный каталог</h2></center>
<table width=50% height=20% align="center" border=1>
    <tr align="center">
        <td>Название книги</td>
        <td>Автор</td>
        <td>Жанр</td>
        <td>Стоимость</td>
    </tr>
    <?php foreach ($array as $value): ?>
        <tr align="center">
            <td>
                <a href="form.php?book_id=<?= $value['book_id'] ?>"> <?= $value['title'] ?> </a>
            </td>
            <td>
                <a href="authors_books.php?author_id=<?=$value['author_id']?>"><?=$value['author']?></a>
            </td>
            <td><a href="genres_books.php?genre_id=<?=$value['genre_id']?>"><?=$value['genre']?></a>
            </td>

            <td><?= $value['price']?></td>
        </tr>
    <?php endforeach; ?>

</table>
</body>
</html>
