<?php
include '../classes/db.class.php';
?>
<?php include "head.php" ?>

<div class="main-user">
<h2>Книжный каталог</h2>
<table width=50% height=20% align="center" border=1>
    <tr align="center" class="user-book-info">
        <th>Название книги</th>
        <th>Автор</th>
        <th>Жанр</th>
        <th>Стоимость</th>
        <th style="display: none"></th>

    </tr>
	<?php
	$bookObject = new Books( new Db() );
	$books      = $bookObject->getAllBooks();

	foreach ( $books as $book ) :
		$authors = array();
		$genres = array();
		?>
        <tr align="center" class="user-books">
            <td><a href="form.php?book_id=<?= $book['book_id'] ?>"> <?= $book['title'] ?> </a></td>
            <td>
				<?php foreach ( $book['authors'] as $author ) {
					$authors[] = '<a href="authors_books.php?author_id=' . $author['author_id'] . '">' . $author['author'] . '</a>';
				} ?>
				<?= implode( ', ', $authors ) ?>
            </td>
            <td>
				<?php foreach ( $book['genres'] as $genre ) {
					$genres[] = '<a href="genres_books.php?genre_id=' . $genre['genre_id'] . '">' .
					            $genre['genre'] . '</a>';
				}
				?>
				<?= implode( ', ', $genres ) ?>
            </td>
            <td><?= $book['price']; ?></td>

            <td><a href="form.php?book_id=<?= $book['book_id'] ?>">Заказать</td>
        </tr>
	<?php endforeach; ?>
</table>
</div>
<?php include "foot.php" ?>
